module.exports={
	todos:[{
		uid:Math.random()
		,descript:'diyidier'
		,completed:false
	},{
		uid:Math.random()
		,descript:'diyidier'
		,completed:true
	},{
		uid:Math.random()
		,descript:'diyidier'
		,completed:true
	}]
	,editing:''
	,filter:'all'
}